apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: udic-edu-server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: udic-edu-server
  ports:
    - port: 5000
      name: 'rest-api'
      targetPort: 5000
    - port: 5001
      name: 'wss'
      targetPort: 5001
